//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUI.Liuy.UI.JBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JBService.WebServiceGetInfoSoap")]
    public interface WebServiceGetInfoSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOne", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.GetOneResponse GetOne(EasyUI.Liuy.UI.JBService.GetOneRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateOne", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.updateOneResponse updateOne(EasyUI.Liuy.UI.JBService.updateOneRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUnOrsetupdefences", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesResponse updateUnOrsetupdefences(EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSelectSend", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.GetSelectSendResponse GetSelectSend(EasyUI.Liuy.UI.JBService.GetSelectSendRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlarmStatistics", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.GetAlarmStatisticsResponse GetAlarmStatistics(EasyUI.Liuy.UI.JBService.GetAlarmStatisticsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlarmStatisticsCount", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountResponse GetAlarmStatisticsCount(EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInformationAll", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.GetInformationAllResponse GetInformationAll(EasyUI.Liuy.UI.JBService.GetInformationAllRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHistory", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.GetHistoryResponse GetHistory(EasyUI.Liuy.UI.JBService.GetHistoryRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSelectSIM", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.GetSelectSIMResponse GetSelectSIM(EasyUI.Liuy.UI.JBService.GetSelectSIMRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSIM", ReplyAction="*")]
        EasyUI.Liuy.UI.JBService.UpdateSIMResponse UpdateSIM(EasyUI.Liuy.UI.JBService.UpdateSIMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOne", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetOneRequestBody Body;
        
        public GetOneRequest() {
        }
        
        public GetOneRequest(EasyUI.Liuy.UI.JBService.GetOneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        public GetOneRequestBody() {
        }
        
        public GetOneRequestBody(string UserName, string Pwd, string id) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOneResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetOneResponseBody Body;
        
        public GetOneResponse() {
        }
        
        public GetOneResponse(EasyUI.Liuy.UI.JBService.GetOneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOneResult;
        
        public GetOneResponseBody() {
        }
        
        public GetOneResponseBody(string GetOneResult) {
            this.GetOneResult = GetOneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateOne", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.updateOneRequestBody Body;
        
        public updateOneRequest() {
        }
        
        public updateOneRequest(EasyUI.Liuy.UI.JBService.updateOneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateOneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content;
        
        public updateOneRequestBody() {
        }
        
        public updateOneRequestBody(string UserName, string Pwd, string id, string Content) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateOneResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.updateOneResponseBody Body;
        
        public updateOneResponse() {
        }
        
        public updateOneResponse(EasyUI.Liuy.UI.JBService.updateOneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateOneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateOneResult;
        
        public updateOneResponseBody() {
        }
        
        public updateOneResponseBody(string updateOneResult) {
            this.updateOneResult = updateOneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUnOrsetupdefencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUnOrsetupdefences", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesRequestBody Body;
        
        public updateUnOrsetupdefencesRequest() {
        }
        
        public updateUnOrsetupdefencesRequest(EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateUnOrsetupdefencesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Status;
        
        public updateUnOrsetupdefencesRequestBody() {
        }
        
        public updateUnOrsetupdefencesRequestBody(string UserName, string Pwd, string id, string Status) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUnOrsetupdefencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUnOrsetupdefencesResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesResponseBody Body;
        
        public updateUnOrsetupdefencesResponse() {
        }
        
        public updateUnOrsetupdefencesResponse(EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateUnOrsetupdefencesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateUnOrsetupdefencesResult;
        
        public updateUnOrsetupdefencesResponseBody() {
        }
        
        public updateUnOrsetupdefencesResponseBody(string updateUnOrsetupdefencesResult) {
            this.updateUnOrsetupdefencesResult = updateUnOrsetupdefencesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSelectSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSelectSend", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetSelectSendRequestBody Body;
        
        public GetSelectSendRequest() {
        }
        
        public GetSelectSendRequest(EasyUI.Liuy.UI.JBService.GetSelectSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSelectSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        public GetSelectSendRequestBody() {
        }
        
        public GetSelectSendRequestBody(string UserName, string Pwd, string id) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSelectSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSelectSendResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetSelectSendResponseBody Body;
        
        public GetSelectSendResponse() {
        }
        
        public GetSelectSendResponse(EasyUI.Liuy.UI.JBService.GetSelectSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSelectSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSelectSendResult;
        
        public GetSelectSendResponseBody() {
        }
        
        public GetSelectSendResponseBody(string GetSelectSendResult) {
            this.GetSelectSendResult = GetSelectSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlarmStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlarmStatistics", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetAlarmStatisticsRequestBody Body;
        
        public GetAlarmStatisticsRequest() {
        }
        
        public GetAlarmStatisticsRequest(EasyUI.Liuy.UI.JBService.GetAlarmStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlarmStatisticsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        public GetAlarmStatisticsRequestBody() {
        }
        
        public GetAlarmStatisticsRequestBody(string UserName, string Pwd, string id) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlarmStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlarmStatisticsResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetAlarmStatisticsResponseBody Body;
        
        public GetAlarmStatisticsResponse() {
        }
        
        public GetAlarmStatisticsResponse(EasyUI.Liuy.UI.JBService.GetAlarmStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlarmStatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAlarmStatisticsResult;
        
        public GetAlarmStatisticsResponseBody() {
        }
        
        public GetAlarmStatisticsResponseBody(string GetAlarmStatisticsResult) {
            this.GetAlarmStatisticsResult = GetAlarmStatisticsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlarmStatisticsCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlarmStatisticsCount", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountRequestBody Body;
        
        public GetAlarmStatisticsCountRequest() {
        }
        
        public GetAlarmStatisticsCountRequest(EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlarmStatisticsCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EndDate;
        
        public GetAlarmStatisticsCountRequestBody() {
        }
        
        public GetAlarmStatisticsCountRequestBody(string UserName, string Pwd, string id, string StartDate, string EndDate) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlarmStatisticsCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlarmStatisticsCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountResponseBody Body;
        
        public GetAlarmStatisticsCountResponse() {
        }
        
        public GetAlarmStatisticsCountResponse(EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlarmStatisticsCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAlarmStatisticsCountResult;
        
        public GetAlarmStatisticsCountResponseBody() {
        }
        
        public GetAlarmStatisticsCountResponseBody(string GetAlarmStatisticsCountResult) {
            this.GetAlarmStatisticsCountResult = GetAlarmStatisticsCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInformationAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInformationAll", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetInformationAllRequestBody Body;
        
        public GetInformationAllRequest() {
        }
        
        public GetInformationAllRequest(EasyUI.Liuy.UI.JBService.GetInformationAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInformationAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        public GetInformationAllRequestBody() {
        }
        
        public GetInformationAllRequestBody(string UserName, string Pwd, string id) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInformationAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInformationAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetInformationAllResponseBody Body;
        
        public GetInformationAllResponse() {
        }
        
        public GetInformationAllResponse(EasyUI.Liuy.UI.JBService.GetInformationAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInformationAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInformationAllResult;
        
        public GetInformationAllResponseBody() {
        }
        
        public GetInformationAllResponseBody(string GetInformationAllResult) {
            this.GetInformationAllResult = GetInformationAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHistory", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetHistoryRequestBody Body;
        
        public GetHistoryRequest() {
        }
        
        public GetHistoryRequest(EasyUI.Liuy.UI.JBService.GetHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EndDate;
        
        public GetHistoryRequestBody() {
        }
        
        public GetHistoryRequestBody(string UserName, string Pwd, string id, string StartDate, string EndDate) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetHistoryResponseBody Body;
        
        public GetHistoryResponse() {
        }
        
        public GetHistoryResponse(EasyUI.Liuy.UI.JBService.GetHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHistoryResult;
        
        public GetHistoryResponseBody() {
        }
        
        public GetHistoryResponseBody(string GetHistoryResult) {
            this.GetHistoryResult = GetHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSelectSIMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSelectSIM", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetSelectSIMRequestBody Body;
        
        public GetSelectSIMRequest() {
        }
        
        public GetSelectSIMRequest(EasyUI.Liuy.UI.JBService.GetSelectSIMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSelectSIMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sim;
        
        public GetSelectSIMRequestBody() {
        }
        
        public GetSelectSIMRequestBody(string UserName, string Pwd, string sim) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.sim = sim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSelectSIMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSelectSIMResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.GetSelectSIMResponseBody Body;
        
        public GetSelectSIMResponse() {
        }
        
        public GetSelectSIMResponse(EasyUI.Liuy.UI.JBService.GetSelectSIMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSelectSIMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSelectSIMResult;
        
        public GetSelectSIMResponseBody() {
        }
        
        public GetSelectSIMResponseBody(string GetSelectSIMResult) {
            this.GetSelectSIMResult = GetSelectSIMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSIMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSIM", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.UpdateSIMRequestBody Body;
        
        public UpdateSIMRequest() {
        }
        
        public UpdateSIMRequest(EasyUI.Liuy.UI.JBService.UpdateSIMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSIMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sim;
        
        public UpdateSIMRequestBody() {
        }
        
        public UpdateSIMRequestBody(string UserName, string Pwd, string id, string sim) {
            this.UserName = UserName;
            this.Pwd = Pwd;
            this.id = id;
            this.sim = sim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSIMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSIMResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyUI.Liuy.UI.JBService.UpdateSIMResponseBody Body;
        
        public UpdateSIMResponse() {
        }
        
        public UpdateSIMResponse(EasyUI.Liuy.UI.JBService.UpdateSIMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSIMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateSIMResult;
        
        public UpdateSIMResponseBody() {
        }
        
        public UpdateSIMResponseBody(string UpdateSIMResult) {
            this.UpdateSIMResult = UpdateSIMResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceGetInfoSoapChannel : EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceGetInfoSoapClient : System.ServiceModel.ClientBase<EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap>, EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap {
        
        public WebServiceGetInfoSoapClient() {
        }
        
        public WebServiceGetInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceGetInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceGetInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceGetInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.GetOneResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.GetOne(EasyUI.Liuy.UI.JBService.GetOneRequest request) {
            return base.Channel.GetOne(request);
        }
        
        public string GetOne(string UserName, string Pwd, string id) {
            EasyUI.Liuy.UI.JBService.GetOneRequest inValue = new EasyUI.Liuy.UI.JBService.GetOneRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.GetOneRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            EasyUI.Liuy.UI.JBService.GetOneResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).GetOne(inValue);
            return retVal.Body.GetOneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.updateOneResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.updateOne(EasyUI.Liuy.UI.JBService.updateOneRequest request) {
            return base.Channel.updateOne(request);
        }
        
        public string updateOne(string UserName, string Pwd, string id, string Content) {
            EasyUI.Liuy.UI.JBService.updateOneRequest inValue = new EasyUI.Liuy.UI.JBService.updateOneRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.updateOneRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            inValue.Body.Content = Content;
            EasyUI.Liuy.UI.JBService.updateOneResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).updateOne(inValue);
            return retVal.Body.updateOneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.updateUnOrsetupdefences(EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesRequest request) {
            return base.Channel.updateUnOrsetupdefences(request);
        }
        
        public string updateUnOrsetupdefences(string UserName, string Pwd, string id, string Status) {
            EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesRequest inValue = new EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            inValue.Body.Status = Status;
            EasyUI.Liuy.UI.JBService.updateUnOrsetupdefencesResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).updateUnOrsetupdefences(inValue);
            return retVal.Body.updateUnOrsetupdefencesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.GetSelectSendResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.GetSelectSend(EasyUI.Liuy.UI.JBService.GetSelectSendRequest request) {
            return base.Channel.GetSelectSend(request);
        }
        
        public string GetSelectSend(string UserName, string Pwd, string id) {
            EasyUI.Liuy.UI.JBService.GetSelectSendRequest inValue = new EasyUI.Liuy.UI.JBService.GetSelectSendRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.GetSelectSendRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            EasyUI.Liuy.UI.JBService.GetSelectSendResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).GetSelectSend(inValue);
            return retVal.Body.GetSelectSendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.GetAlarmStatisticsResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.GetAlarmStatistics(EasyUI.Liuy.UI.JBService.GetAlarmStatisticsRequest request) {
            return base.Channel.GetAlarmStatistics(request);
        }
        
        public string GetAlarmStatistics(string UserName, string Pwd, string id) {
            EasyUI.Liuy.UI.JBService.GetAlarmStatisticsRequest inValue = new EasyUI.Liuy.UI.JBService.GetAlarmStatisticsRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.GetAlarmStatisticsRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            EasyUI.Liuy.UI.JBService.GetAlarmStatisticsResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).GetAlarmStatistics(inValue);
            return retVal.Body.GetAlarmStatisticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.GetAlarmStatisticsCount(EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountRequest request) {
            return base.Channel.GetAlarmStatisticsCount(request);
        }
        
        public string GetAlarmStatisticsCount(string UserName, string Pwd, string id, string StartDate, string EndDate) {
            EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountRequest inValue = new EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            EasyUI.Liuy.UI.JBService.GetAlarmStatisticsCountResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).GetAlarmStatisticsCount(inValue);
            return retVal.Body.GetAlarmStatisticsCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.GetInformationAllResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.GetInformationAll(EasyUI.Liuy.UI.JBService.GetInformationAllRequest request) {
            return base.Channel.GetInformationAll(request);
        }
        
        public string GetInformationAll(string UserName, string Pwd, string id) {
            EasyUI.Liuy.UI.JBService.GetInformationAllRequest inValue = new EasyUI.Liuy.UI.JBService.GetInformationAllRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.GetInformationAllRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            EasyUI.Liuy.UI.JBService.GetInformationAllResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).GetInformationAll(inValue);
            return retVal.Body.GetInformationAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.GetHistoryResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.GetHistory(EasyUI.Liuy.UI.JBService.GetHistoryRequest request) {
            return base.Channel.GetHistory(request);
        }
        
        public string GetHistory(string UserName, string Pwd, string id, string StartDate, string EndDate) {
            EasyUI.Liuy.UI.JBService.GetHistoryRequest inValue = new EasyUI.Liuy.UI.JBService.GetHistoryRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.GetHistoryRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            EasyUI.Liuy.UI.JBService.GetHistoryResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).GetHistory(inValue);
            return retVal.Body.GetHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.GetSelectSIMResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.GetSelectSIM(EasyUI.Liuy.UI.JBService.GetSelectSIMRequest request) {
            return base.Channel.GetSelectSIM(request);
        }
        
        public string GetSelectSIM(string UserName, string Pwd, string sim) {
            EasyUI.Liuy.UI.JBService.GetSelectSIMRequest inValue = new EasyUI.Liuy.UI.JBService.GetSelectSIMRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.GetSelectSIMRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.sim = sim;
            EasyUI.Liuy.UI.JBService.GetSelectSIMResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).GetSelectSIM(inValue);
            return retVal.Body.GetSelectSIMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyUI.Liuy.UI.JBService.UpdateSIMResponse EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap.UpdateSIM(EasyUI.Liuy.UI.JBService.UpdateSIMRequest request) {
            return base.Channel.UpdateSIM(request);
        }
        
        public string UpdateSIM(string UserName, string Pwd, string id, string sim) {
            EasyUI.Liuy.UI.JBService.UpdateSIMRequest inValue = new EasyUI.Liuy.UI.JBService.UpdateSIMRequest();
            inValue.Body = new EasyUI.Liuy.UI.JBService.UpdateSIMRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pwd = Pwd;
            inValue.Body.id = id;
            inValue.Body.sim = sim;
            EasyUI.Liuy.UI.JBService.UpdateSIMResponse retVal = ((EasyUI.Liuy.UI.JBService.WebServiceGetInfoSoap)(this)).UpdateSIM(inValue);
            return retVal.Body.UpdateSIMResult;
        }
    }
}
