// <auto-generated />
namespace EasyUI.Liuy.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(price));
        
        string IMigrationMetadata.Id
        {
            get { return "201311180656121_price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
